# Generated by Django 3.2.23 on 2023-12-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsoporte',
            name='chat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticketsoporte',
            name='fechaFinalizacionReal',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
