# Generated by Django 3.2.23 on 2023-12-05 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsoporte',
            name='idSolicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_soporte_solicitante', to='soporte.solicitante'),
        ),
    ]
