# Generated by Django 3.2.23 on 2023-12-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0002_auto_20231215_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsoporte',
            name='facturar',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketsoporte',
            name='fechaFinalizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketsoporte',
            name='fechaInicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketsoporte',
            name='prioridad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
